apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello
  labels:
    app: spring-boot-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-hello
  template:
    metadata:
      labels:
        app: spring-boot-hello
    spec:
      containers:
        - name: spring-boot-hello
          image: your-docker-registry/spring-boot-hello:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFIL

